spring.application.name=expert-testes
server.port=9200

# ===============================
# H2 connection
# ===============================
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# H2 client
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


logging.level.org.hibernate.orm.connections.pooling=WARN
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
#  Hikari CP
# ===============================
logging.level.com.zaxxer.hikari=INFO
spring.datasource.hikari.minimum-idle=8
spring.datasource.hikari.maximum-pool-size=16
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ==================================================
# ========== CONFIGURACOES DO TOKEN JWT ============
# ==================================================

#Obs: Comentado porque esta sendo usado o bean decoder em ResourceServerConfig
# Usando a chave publica via API do authorization server
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9200/oauth2/jwks

# Usando chave publica via arquivo
#spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keystore/algafood-pkey.pem

cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

# ===============================
# Geracao de scripts
# ===============================

# Forca usar entidades JPA (@Entity), mapeamentos (@Column, @JoinColumn, etc.), eh mais previsivel para gerar o schema
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata

# indica quais scripts DDL devem ser gerados
# opcoes aceitas: none, create, drop, drop-and-create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=none

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/ddl.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=ddl.sql

spring.jpa.properties.hibernate.hbm2ddl.charset_name=UTF-8
spring.jpa.properties.hibernate.hbm2ddl.delimiter=;

# Forca o Hibernate a lidar com BLOB/CLOB de forma independente do banco, evitando erros de driver JDBC
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================
# Configuracao de envio de email
# ===============================

# Obs: Tem que ser gerado uma senha de app pela conta do gmail: https://myaccount.google.com/
# fluxo: Acessar sua conta no Google -> Seguranca -> Validacao em duas etapas -> Senhas de app

# Define o servidor SMTP para enviar e-mails, se nao existir usa o padrao: smtp.gmail.com (servidor do Gmail)
spring.mail.host=${EMAIL_HOST:smtp.gmail.com}

# Porta do servidor SMTP. 587 eh a porta padrao para envio com STARTTLS (seguro)
spring.mail.port=${EMAIL_PORT:587}

# Indica que o servidor SMTP exige autenticacao (usuario e senha)
spring.mail.properties.mail.smtp.auth=true

# Ativa o STARTTLS, que criptografa a conexao, recomendado para enviar credenciais com seguranca
spring.mail.properties.mail.smtp.starttls.enable=true

# Usuario do e-mail (login SMTP)
spring.mail.username=${EMAIL_USERNAME:test@gmail.com}

# Senha do e-mail
spring.mail.password=${EMAIL_PASSWORD:123456}

email.password-recover.token.minutes=${PASSWORD_RECOVER_TOKEN_MINUTES:30}

# Seria a url do front-end que vai ser enviado no email
email.password-recover.uri=${PASSWORD_RECOVER_URI:http://localhost:9200/recover-password}

